
package it.water.connectors.jobscheduler.service.rest;

import it.water.connectors.jobscheduler.api.JobSchedulerApi;
import it.water.connectors.jobscheduler.api.rest.JobSchedulerRestApi;
import it.water.core.api.service.rest.FrameworkRestController;
import it.water.core.interceptors.annotations.Inject;
import lombok.Setter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;


/**
 * @Generated by Water Generator
 * Rest Api Class for JobScheduler entity.
 *
 */
@FrameworkRestController(referredRestApi = JobSchedulerRestApi.class)
public class JobSchedulerRestControllerImpl  implements JobSchedulerRestApi {
    @SuppressWarnings("java:S1068") //still mantain the variable even if not used
    private static Logger log = LoggerFactory.getLogger(JobSchedulerRestControllerImpl.class.getName());
    
    @Inject
    @Setter
    private JobSchedulerApi jobSchedulerApi;
    // Placeholder controller kept only for API compatibility.
    // No concrete JAX-RS methods are exposed at the moment.
    // If real REST endpoints are added, use JobSchedulerApi to keep permission checks in place.

}
